### ISSUE TITLE
Fashion200k data

### ISSUE THREAD

**Issue by Crystal-twy998** [haokunwen/DQU-CIR#3]
The issue has been resolved, I didn't read carefully.

**Comment by haokunwen** [comment]
Hi~ I'm not entirely sure what you actually need. As you can see from the datasets.py file, the triplets in the Fashion200k dataset are constructed on the fly. Specifically, it first mines the image pairs that have one different word in their descriptions and then utilizes the template "replace A with B". So, in actuality, there isn't a JSON file for the triplet data like there is for other datasets. In our work, we considered "B" as the keywords.
